-- ================================================================
-- docs-agent — Database Schema
-- PostgreSQL 17 + pgvector
-- ================================================================
-- Bootstrap script. For incremental changes, add migrations under
-- supabase/migrations/. The match_documents RPC mirrors the pattern
-- used in production at Mavryx Assistant (1536-dim vectors,
-- metadata @> filter).
-- ================================================================

-- ── Extensions ───────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS vector      WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;

-- ── sources ───────────────────────────────────────────────────────
-- One row per crawled URL. Lets us track ingestion runs, detect new
-- pages on re-crawl, and dedupe by content hash.
CREATE TABLE IF NOT EXISTS public.sources (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  url           text UNIQUE NOT NULL,
  title         text,
  content_hash  text,                       -- sha256 of page text — dedupe across re-crawls
  section_count int NOT NULL DEFAULT 0,
  crawled_at    timestamptz NOT NULL DEFAULT now(),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sources_url  ON public.sources (url);
CREATE INDEX IF NOT EXISTS idx_sources_hash ON public.sources (content_hash);

-- ── documents (KB chunks — RAG) ──────────────────────────────────
-- Each row is one chunk. Metadata carries everything the agent needs
-- for citations (url, title, section, anchor) and any future filters
-- (e.g. doc_family if we ever index multiple sites).
CREATE TABLE IF NOT EXISTS public.documents (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id  uuid REFERENCES public.sources(id) ON DELETE CASCADE,
  content    text NOT NULL,
  metadata   jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedding  extensions.vector(1536),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- HNSW index is faster + more accurate than IVFFlat for this scale.
-- Cosine distance because OpenAI embeddings are normalized.
CREATE INDEX IF NOT EXISTS idx_documents_embedding
  ON public.documents USING hnsw (embedding extensions.vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS idx_documents_source_id
  ON public.documents (source_id);

CREATE INDEX IF NOT EXISTS idx_documents_metadata_doc_family
  ON public.documents ((metadata->>'doc_family'));

-- ── match_documents RPC (vector similarity search) ───────────────
-- Same shape as Mavryx production. `filter` is matched against
-- metadata using the @> containment operator, so callers can scope
-- to {"doc_family":"anthropic-docs"} etc. without changing SQL.
CREATE OR REPLACE FUNCTION public.match_documents(
  query_embedding extensions.vector(1536),
  match_count     int DEFAULT 8,
  filter          jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  id          bigint,
  content     text,
  metadata    jsonb,
  similarity  float
)
LANGUAGE plpgsql STABLE PARALLEL SAFE AS $$
BEGIN
  RETURN QUERY
  SELECT
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) AS similarity
  FROM public.documents d
  WHERE d.metadata @> filter
  ORDER BY d.embedding <=> query_embedding
  LIMIT match_count;
END $$;

-- ── eval_runs (eval persistence) ─────────────────────────────────
-- Each eval invocation writes one row here, plus rows per question
-- in eval_results. Lets us watch metrics move as we tune.
CREATE TABLE IF NOT EXISTS public.eval_runs (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_model   text NOT NULL,
  judge_model   text NOT NULL,
  dataset_name  text NOT NULL,
  num_questions int NOT NULL,
  -- Aggregate metrics — see eval/metrics.py
  precision_at_5    numeric(4,3),
  recall_at_5       numeric(4,3),
  mrr               numeric(4,3),
  avg_faithfulness  numeric(4,3),
  avg_completeness  numeric(4,3),
  avg_citation_ok   numeric(4,3),
  hallucination_rate numeric(4,3),
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.eval_results (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id          uuid NOT NULL REFERENCES public.eval_runs(id) ON DELETE CASCADE,
  question        text NOT NULL,
  expected_urls   text[] NOT NULL DEFAULT ARRAY[]::text[],
  retrieved_urls  text[] NOT NULL DEFAULT ARRAY[]::text[],
  precision_at_k  numeric(4,3),
  recall_at_k     numeric(4,3),
  answer          text,
  judge_scores    jsonb,
  judge_notes     text,
  latency_ms      int,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_eval_results_run ON public.eval_results (run_id);

-- ── Row-Level Security ───────────────────────────────────────────
-- For the assessment, the API uses the service_role key (no end-user
-- auth). RLS is enabled and policies are restrictive by default,
-- which means anon/auth users see nothing — service_role bypasses.
-- This is a deliberate "secure-by-default" choice, easy to relax
-- later once an auth model is decided.
ALTER TABLE public.sources       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_runs     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_results  ENABLE ROW LEVEL SECURITY;

-- (No permissive policies. Service-role bypasses RLS by design.)
